//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCodeCounter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceCodeCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon My_Computer {
            get {
                object obj = ResourceManager.GetObject("My_Computer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart copied to clipboad..
        /// </summary>
        internal static string Resource_ChartCopiedToClipboard {
            get {
                return ResourceManager.GetString("Resource_ChartCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap (*.bmp)|*.bmp|JPEG (*.jpg)|*.jpg|EMF-Plus (*.emf)|*.emf|EMF-Dual (*.emf)|*.emf|EMF (*.emf)|*.emf|PNG (*.png)|*.png|GIF (*.gif)|*.gif|TIFF (*.tif)|*.tif.
        /// </summary>
        internal static string Resource_ChartFileSaveFormat {
            get {
                return ResourceManager.GetString("Resource_ChartFileSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Resource_Clipboard {
            get {
                return ResourceManager.GetString("Resource_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Project.
        /// </summary>
        internal static string Resource_DefaultProject {
            get {
                return ResourceManager.GetString("Resource_DefaultProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path..
        /// </summary>
        internal static string Resource_InvalidFilePath {
            get {
                return ResourceManager.GetString("Resource_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait ....
        /// </summary>
        internal static string Resource_PleaseWait {
            get {
                return ResourceManager.GetString("Resource_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, analysing ....
        /// </summary>
        internal static string Resource_PleaseWaitAnalysing {
            get {
                return ResourceManager.GetString("Resource_PleaseWaitAnalysing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, preparing ....
        /// </summary>
        internal static string Resource_PleaseWaitPreparing {
            get {
                return ResourceManager.GetString("Resource_PleaseWaitPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, scanning ....
        /// </summary>
        internal static string Resource_PleaseWaitScanning {
            get {
                return ResourceManager.GetString("Resource_PleaseWaitScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting, Please wait ....
        /// </summary>
        internal static string Resource_PleaseWaitStarting {
            get {
                return ResourceManager.GetString("Resource_PleaseWaitStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Scanner.
        /// </summary>
        internal static string Resource_ProjectScanner {
            get {
                return ResourceManager.GetString("Resource_ProjectScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Complete..
        /// </summary>
        internal static string Resource_ScanComplete {
            get {
                return ResourceManager.GetString("Resource_ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type not supported..
        /// </summary>
        internal static string Resource_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Resource_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
